//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playlister.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Profiles = new HashSet<Profile>();
        }
    
        public int Person_ID { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public int Role_ID { get; set; }
        public string User_Name { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string E_Mail { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Facebook_Key { get; set; }
        public string Twitter_Key { get; set; }
        public string Spotify_Key { get; set; }
        public int Profile_ID { get; set; }
        public int Party_Owner_ID { get; set; }
        public Nullable<int> Party_Participant { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual Person_Role Person_Role { get; set; }
        public virtual User_Credential User_Credentials { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
    }
}
