//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playlister.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_Role
    {
        public Person_Role()
        {
            this.People = new HashSet<Person>();
        }
    
        public int Person_Role_ID { get; set; }
        public string Role_Title { get; set; }
        public int Role_Permission_Combo_ID { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
        public virtual Role_Permission Role_Permission { get; set; }
    }
}
