//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playlister.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Playlist
    {
        public Playlist()
        {
            this.Parties = new HashSet<Party>();
        }
    
        public int Playlist_ID { get; set; }
        public string Playlist_Title { get; set; }
        public string Song_ID { get; set; }
        public string Song_Title { get; set; }
        public Nullable<int> Song_Vote { get; set; }
        public int Party_ID { get; set; }
    
        public virtual ICollection<Party> Parties { get; set; }
        public virtual Song Song { get; set; }
    }
}
