//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playlister.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int Person_ID { get; set; }
        public int Profile_ID { get; set; }
        public string Profile_Name { get; set; }
        public byte[] Profile_Picture { get; set; }
        public string Bio { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
