//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playlister.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_Permission
    {
        public Role_Permission()
        {
            this.Person_Role = new HashSet<Person_Role>();
        }
    
        public int Role_Permission_Combo_ID { get; set; }
        public bool Permission1 { get; set; }
        public bool Permission2 { get; set; }
        public int PermissionN { get; set; }
    
        public virtual ICollection<Person_Role> Person_Role { get; set; }
    }
}
