//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playlister.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Credential
    {
        public User_Credential()
        {
            this.People = new HashSet<Person>();
        }
    
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string Security_Question_1 { get; set; }
        public string Security_Answer_1 { get; set; }
        public string Security_Question_2 { get; set; }
        public string Security_Answer_2 { get; set; }
        public int CredentialSource { get; set; }
    
        public virtual Credential_Source_Code_Table Credential_Source_Code_Table { get; set; }
        public virtual ICollection<Person> People { get; set; }
    }
}
